### PR TITLE
Add shell linter

### PR DESCRIPTION
**Pull request by pboothe**
Also make all our shell scripts pass the shell linter.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/git-hooks/9)

### CODE REVIEW

**Comment by yachang** [comment]
Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---

*[prepare-commit-msg, line 82 at r1](https://reviewable.io/reviews/m-lab/git-hooks/9#-LB41Etr7GNrZ491IUiZ:-LB41Etr7GNrZ491IUi_:b71cn1s) ([raw file](https://github.com/m-lab/git-hooks/blob/127d73054799bc31d63600ec2f08c655d2c3a982/prepare-commit-msg#L82)):*
> ```
>         fi
>       done | grep -q '^#!/bin/bash\b'); then
>     if which shellcheck; then
> ```

Do you need to modify travis yaml file to preinstall shellcheck?

---


*Comments from [Reviewable](https://reviewable.io/reviews/m-lab/git-hooks/9)*

**Comment by pboothe** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[prepare-commit-msg, line 82 at r1](https://reviewable.io/reviews/m-lab/git-hooks/9#-LB41Etr7GNrZ491IUiZ:-LB6Vq368IH4BzlbkaZP:bbfup1m) ([raw file](https://github.com/m-lab/git-hooks/blob/127d73054799bc31d63600ec2f08c655d2c3a982/prepare-commit-msg#L82)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

Do you need to modify travis yaml file to preinstall shellcheck?
</blockquote></details>

These checks are done on a person's local computer after they type `git commit`. Travis is uninvolved.

---


*Comments from [Reviewable](https://reviewable.io/reviews/m-lab/git-hooks/9)*

**Comment by pboothe** [comment]
At @yachang's request, added @stephen-soltesz for shell readability review.

**Comment by stephen-soltesz** [comment]
Reviewed 3 of 4 files at r1.
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[prepare-commit-msg, line 91 at r3](https://reviewable.io/reviews/m-lab/git-hooks/9#-LBM-6Qh70ugwLvAhOb2:-LBM-6Qh70ugwLvAhOb3:b3tgt56) ([raw file](https://github.com/m-lab/git-hooks/blob/f899922b92ea8622d14576a8409ce76cd4fc623b/prepare-commit-msg#L91)):*
> ```
>         git ls-files | grep -q '\.sh$'
>         git ls-files | while read -r; do
>           if [[ -f $REPLY ]] && (head -n1 "${REPLY}" | grep -q '^#!/bin/bash\b'); then
> ```

Can we combine the outer and inner checks? It looks like the logic is repeated, and since ls-files only returns files in the repo, if there is a valid shell script we'll want to run shellcheck on it.

---

*[python-prepare-commit-msg, line 31 at r3](https://reviewable.io/reviews/m-lab/git-hooks/9#-LBM-hVo5GTNdrMNRA1Y:-LBM-hVp-Eqire9PjGW6:bpuyuvn) ([raw file](https://github.com/m-lab/git-hooks/blob/f899922b92ea8622d14576a8409ce76cd4fc623b/python-prepare-commit-msg#L31)):*
> ```
> fi
> 
> pythonfiles() {
> ```

I like this pattern.

---


*Comments from [Reviewable](https://reviewable.io/reviews/m-lab/git-hooks/9)*

**Comment by pboothe** [comment]
Review status: 3 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[prepare-commit-msg, line 91 at r3](https://reviewable.io/reviews/m-lab/git-hooks/9#-LBM-6Qh70ugwLvAhOb2:-LBMUfaCBvOoKWwOj8ig:b-896fix) ([raw file](https://github.com/m-lab/git-hooks/blob/f899922b92ea8622d14576a8409ce76cd4fc623b/prepare-commit-msg#L91)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Can we combine the outer and inner checks? It looks like the logic is repeated, and since ls-files only returns files in the repo, if there is a valid shell script we'll want to run shellcheck on it.
</blockquote></details>

Done.

---

*[python-prepare-commit-msg, line 31 at r3](https://reviewable.io/reviews/m-lab/git-hooks/9#-LBM-hVo5GTNdrMNRA1Y:-LBMUhpO9X7F_remy01j:b4uzeh5) ([raw file](https://github.com/m-lab/git-hooks/blob/f899922b92ea8622d14576a8409ce76cd4fc623b/python-prepare-commit-msg#L31)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I like this pattern.
</blockquote></details>

So I stole it for shellfiles too!

---


*Comments from [Reviewable](https://reviewable.io/reviews/m-lab/git-hooks/9)*

**Comment by pboothe** [comment]
PTAL

---

Review status: 3 of 4 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/m-lab/git-hooks/9#-:-LBMUlabEKJhbOsuGgsv:bb71pro)*

**Comment by stephen-soltesz** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/m-lab/git-hooks/9#-:-LBMvKUoBaqAd_fYeY0f:bnfp4nl)*

**Pull request merged**
